<?php
namespace frontend\modules\post\models\forms;


use Yii;
use yii\base\Model;
use frontend\components\Debug;
use frontend\modules\post\models\Comment;

class CommentForm extends Model
{

    public $text;


    public function rules()
    {
        return [

            [['text'], 'string', 'max' => 500, 'min' => 3],
            [['text'], 'required'],
        ];
    }

    public function beforeValidate()
    {
        $this->text = strip_tags($this->text); // удаляем теги
        $this->text = preg_quote($this->text); //екранирование

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function save($user_id, $post_id){

        $comment = new Comment();

        $comment->text = $this->text;
        $comment->user_id = $user_id;
        $comment->post_id = $post_id;

        return $comment->save();
    }




}